version: "3.5"

services:
  mssql:
    container_name: utmn_dbs_mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "123456"
    volumes:
      - mssql:/var/opt/mssql
    networks:
      - utmn_dbs
    restart: unless-stopped

networks:
  utmn_dbs:
    driver: bridge

volumes:
  mssql:
